version: '3.8'

services:
  mysql:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: bakery_system
    ports:
      - "3333:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PASSWORD: test123
      DB_PORT: 3306
      DB_NAME: bakery_system
    restart: unless-stopped

volumes:
  mysql_data: